apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ name }}
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  gcp:
    sqlInstances:
      - name: tiltakspenger-scheduler
        type: POSTGRES_14
        diskAutoresize: {{ sqlInstances.diskAutoresize }}
        pointInTimeRecovery: {{ sqlInstances.pointInTimeRecovery }}
        databases:
          - name: scheduler
            envVarPrefix:
              DB
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
  kafka:
    pool: {{ kafka.pool }}
  secureLogs:
    enabled: true
